import * as React from "react";
import type { ViewStyle } from "react-native";
// Generated by `npm run build:tokens` — fully-resolved semantic tokens (RN can't use CSS vars).
import { light } from "../../../build/rn/theme.light";
import { dark } from "../../../build/rn/theme.dark";

export type NemoTheme = typeof light;

const ThemeContext = React.createContext<NemoTheme>(light);

export function NemoThemeProvider({
  scheme = "light",
  children,
}: {
  scheme?: "light" | "dark";
  children: React.ReactNode;
}) {
  return (
    <ThemeContext.Provider value={scheme === "dark" ? (dark as unknown as NemoTheme) : light}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useNemoTheme = () => React.useContext(ThemeContext);

/**
 * Subtle card elevation. The Figma tokens are Material-3 (tonal elevation, no
 * box-shadow), so this is a framework-level default — not a token — matching
 * the web's Tailwind `shadow-sm`.
 */
export const nemoCardShadow: ViewStyle = {
  shadowColor: "#0f1219",
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.08,
  shadowRadius: 2,
  elevation: 2,
};

export { light, dark };
